# Generated by Django 4.1.7 on 2023-07-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['-created_at']},
        ),
    ]
