# Generated by Django 4.1.7 on 2023-07-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_alter_aviso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['created_at']},
        ),
    ]
