# Generated by Django 4.1.7 on 2023-06-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_exercicio', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicial', models.DateTimeField(blank=True, null=True)),
                ('data_final', models.DateTimeField(blank=True, null=True)),
                ('data_inicial_validacao', models.DateTimeField(blank=True, null=True)),
                ('data_final_validacao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avaliacoes.grupoavaliacao')),
            ],
        ),
    ]
