# Generated by Django 4.1.7 on 2023-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_final_validacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_inicial_validacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
