# Generated by Django 4.1.7 on 2023-04-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_inicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
