# Generated by Django 4.1.7 on 2023-06-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('criterio_texto', models.CharField(max_length=500)),
                ('exigibilidade', models.CharField(choices=[('E', 'Essencial'), ('O', 'Obrigatório'), ('R', 'Recomendado')], max_length=1)),
                ('matriz', models.CharField(choices=[('C', 'Comum'), ('E', 'Executivo'), ('L', 'Legislativo'), ('J', 'Judiciário'), ('T', 'Tribunal de Contas'), ('M', 'Ministério Púbico'), ('D', 'Defensoria Pública'), ('I', 'Administração Indireta')], max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('cod',),
            },
        ),
        migrations.CreateModel(
            name='CriterioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao_texto', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('peso', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='imagem_evidencia')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_avaliacao', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JustificativaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', 'Iniciado'), ('E', 'Editando'), ('F', 'Finalizado UG'), ('AV', 'Aguardando Validação'), ('EV', 'Em Validação'), ('V', 'Validado')], default='I', max_length=2)),
                ('indice', models.FloatField(default=0)),
                ('nivel', models.CharField(default='Inexistente', max_length=50)),
                ('essenciais', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.BooleanField(default=False)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('C', 'Controle Interno'), ('T', 'Tribunal de Contas'), ('A', 'Atricon')], max_length=1)),
                ('motivo', models.CharField(choices=[('C', (('AI', 'Andamento Iniciado'), ('PC', 'Envio Para Revisão da Avaliação'))), ('T', (('IT', 'Andamento Iniciado pelo Tribunal'), ('EA', 'Envio para Análise do Tribunal'), ('RT', 'Envio para Revisão do Tribunal'))), ('A', (('EC', 'Envio para Conclusão'),))], max_length=2)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.questionario')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
