# Generated by Django 4.1.7 on 2023-04-16 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionarios', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkevidencia',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.resposta'),
        ),
        migrations.AddField(
            model_name='imagemevidencia',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.resposta'),
        ),
        migrations.AddField(
            model_name='criterioitem',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.criterio'),
        ),
        migrations.AddField(
            model_name='criterioitem',
            name='item_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.itemavaliacao'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.avaliacao'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='dimensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.dimensao'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='itens_avaliacao',
            field=models.ManyToManyField(through='questionarios.CriterioItem', to='questionarios.itemavaliacao'),
        ),
        migrations.AlterUniqueTogether(
            name='questionario',
            unique_together={('avaliacao', 'entidade')},
        ),
        migrations.AlterUniqueTogether(
            name='criterioitem',
            unique_together={('criterio', 'item_avaliacao')},
        ),
    ]
