# Generated by Django 4.1.7 on 2023-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='motivo',
            field=models.CharField(choices=[('AI', 'Andamento Iniciado'), ('ET', 'Enviado para o Tribunal'), ('EA', 'Enviado para Atricon'), ('EC', 'Enviado para o Controle Interno')], default='AI', max_length=2),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='setor',
            field=models.CharField(choices=[('C', 'Controle Interno'), ('T', 'Tribunal de Contas'), ('A', 'Atricon')], default='C', max_length=1),
        ),
        migrations.DeleteModel(
            name='MotivoTramitacao',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
