# Generated by Django 4.1.7 on 2023-04-18 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionarios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('C', 'Controle Interno'), ('T', 'Tribunal de Contas'), ('A', 'Atricon')], default='C', max_length=1)),
                ('situacao', models.CharField(choices=[('AI', 'Andamento Iniciado'), ('ET', 'Enviado para o Tribunal'), ('EA', 'Enviado para Atricon'), ('EC', 'Enviado para o Controle Interno')], default='AI', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.questionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
