# Generated by Django 4.1.7 on 2023-06-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='status',
            field=models.CharField(choices=[('I', 'Iniciado'), ('E', 'Em Avaliação'), ('F', 'Finalizado UG'), ('AV', 'Aguardando Validação'), ('EV', 'Em Validação'), ('V', 'Validado')], default='I', max_length=2),
        ),
    ]
