# Generated by Django 4.1.7 on 2023-04-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_tramitacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='imagemevidencia',
            name='imagem',
            field=models.FileField(upload_to='imagem_evidencia'),
        ),
    ]
