# Generated by Django 4.1.7 on 2023-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_tramitaca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitaca',
            name='situacao',
            field=models.CharField(choices=[('C', 'Criação'), ('ET', 'Enviado para o Tribunal'), ('EA', 'Enviado para Atricon'), ('EC', 'Enviado para o Controle Interno')], default='C', max_length=2),
        ),
    ]
