# Generated by Django 4.1.7 on 2023-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0004_alter_tramitacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemevidencia',
            name='imagem',
            field=models.CharField(max_length=200),
        ),
    ]
