# Generated by Django 4.1.7 on 2023-04-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0004_alter_tramitacao_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkevidencia',
            name='link',
            field=models.TextField(),
        ),
    ]
