# Generated by Django 4.1.7 on 2023-04-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0005_alter_linkevidencia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='motivo',
            field=models.CharField(choices=[('C', (('AI', 'Andamento Iniciado'), ('EA', 'Envio para Análise do Tribunal'))), ('T', (('IT', 'Andamento Iniciado pelo Tribunal'), ('RC', 'Envio para Revisão do Controle Interno'), ('PC', 'Para Correção do Controle Interno'), ('EC', 'Envio para Conclusão da Atricon'))), ('A', (('RT', 'Enviado para Revisão do Tribunal'), ('CT', 'Para Correção do Tribunal'), ('A', 'Concluído')))], max_length=2),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='setor',
            field=models.CharField(choices=[('C', 'Controle Interno'), ('T', 'Tribunal de Contas'), ('A', 'Atricon')], max_length=1),
        ),
    ]
