# Generated by Django 4.1.7 on 2023-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0006_alter_tramitacao_motivo_alter_tramitacao_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='motivo',
            field=models.CharField(choices=[('C', (('AI', 'Andamento Iniciado'), ('PC', 'Envio Para Revisão da Avaliação'))), ('T', (('IT', 'Andamento Iniciado pelo Tribunal'), ('EA', 'Envio para Análise do Tribunal'), ('RT', 'Envio para Revisão do Tribunal'))), ('A', (('EC', 'Envio para Conclusão'),))], max_length=2),
        ),
    ]
