# Generated by Django 4.1.7 on 2023-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0007_alter_tramitacao_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='matriz',
            field=models.CharField(choices=[('C', 'Comum'), ('E', 'Executivo'), ('L', 'Legislativo'), ('J', 'Judiciário'), ('T', 'Tribunal de Contas'), ('M', 'Ministério Púbico'), ('D', 'Defensoria Pública')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
