# Generated by Django 4.1.7 on 2023-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0009_criterio_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemevidencia',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
