# Generated by Django 4.1.7 on 2023-05-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0010_imagemevidencia_justificativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemevidencia',
            name='justificativa',
        ),
        migrations.CreateModel(
            name='JustificativaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.resposta')),
            ],
        ),
    ]
