# Generated by Django 4.1.7 on 2023-05-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0015_dimensao_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
