# Generated by Django 4.1.7 on 2023-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0016_alter_resposta_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
