# Generated by Django 4.1.7 on 2023-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0018_alter_questionario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='indice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
