# Generated by Django 4.1.7 on 2023-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0019_questionario_indice_questionario_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='indice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='nivel',
            field=models.CharField(default='Inexistente', max_length=50),
        ),
    ]
