# Generated by Django 4.1.7 on 2023-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0020_alter_questionario_indice_alter_questionario_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='essenciais',
            field=models.FloatField(default=0),
        ),
    ]
