# Generated by Django 4.1.7 on 2023-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0022_alter_criterio_criterio_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='cod',
            field=models.FloatField(default=0),
        ),
    ]
