# Generated by Django 4.1.7 on 2023-05-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0023_alter_criterio_cod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterio',
            options={'ordering': ('cod',)},
        ),
    ]
