# Generated by Django 4.1.7 on 2023-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0026_alter_criterio_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='cod',
            field=models.CharField(max_length=10),
        ),
    ]
