# Generated by Django 4.1.7 on 2023-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0027_alter_criterio_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='matriz',
            field=models.CharField(choices=[('C', 'Comum'), ('E', 'Executivo'), ('L', 'Legislativo'), ('J', 'Judiciário'), ('T', 'Tribunal de Contas'), ('M', 'Ministério Púbico'), ('D', 'Defensoria Pública'), ('I', 'Administração Indireta')], max_length=1),
        ),
    ]
