# Generated by Django 4.1.7 on 2023-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0028_alter_criterio_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='cod',
            field=models.IntegerField(),
        ),
    ]
