# Generated by Django 4.1.7 on 2023-06-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0029_alter_criterio_cod'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='criterio',
            index=models.Index(fields=['matriz'], name='questionari_matriz_2be1d2_idx'),
        ),
    ]
