# Generated by Django 4.1.7 on 2023-04-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entidade',
            field=models.ManyToManyField(to='entidades.entidade'),
        ),
    ]
