# Generated by Django 4.1.7 on 2023-04-19 21:41

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        ('usuarios', '0002_alter_user_entidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entidade',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='municipio', chained_model_field='municipio', to='entidades.entidade'),
        ),
    ]
