# Generated by Django 4.1.7 on 2023-05-31 05:49

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_alter_entidade_options'),
        ('usuarios', '0006_user_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entidade',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='municipio', chained_model_field='municipio', to='entidades.entidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='funcao',
            field=models.CharField(choices=[('C', 'Controle Interno'), ('T', 'Tribunal de Contas'), ('A', 'Atricon')], default='C', max_length=1),
        ),
    ]
