# Generated by Django 4.1.7 on 2023-06-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setor',
            field=models.CharField(choices=[('C', 'Controle Interno'), ('T', 'Tribunal de Contas'), ('A', 'Atricon')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='funcao',
            field=models.CharField(choices=[('A', 'Avaliador'), ('V', 'Validador'), ('C', 'Coordenador')], default='A', max_length=1),
        ),
    ]
