# Generated by Django 4.1.7 on 2023-06-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('poder', models.CharField(choices=[('D', 'Defensoria Pública'), ('E', 'Executivo'), ('J', 'Judiciário'), ('L', 'Legislativo'), ('M', 'Ministério Público'), ('T', 'Tribunal de Contas'), ('I', 'Administração Indireta')], max_length=1)),
                ('esfera', models.CharField(choices=[('D', 'Distrital'), ('E', 'Estadual'), ('F', 'Federal'), ('M', 'Municipal')], max_length=1)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['municipio'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('ibge', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2)),
                ('capital', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['uf'], name='entidades_m_uf_77a9e0_idx'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.municipio'),
        ),
        migrations.AddIndex(
            model_name='entidade',
            index=models.Index(fields=['poder'], name='entidades_e_poder_bece8d_idx'),
        ),
    ]
