# Generated by Django 4.1.7 on 2023-05-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_municipio_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='poder',
            field=models.CharField(choices=[('D', 'Defensoria Pública'), ('E', 'Executivo'), ('J', 'Judiciário'), ('L', 'Legislativo'), ('M', 'Ministério Público'), ('T', 'Tribunal de Contas'), ('I', 'Administração Indireta')], max_length=1),
        ),
    ]
