# Generated by Django 4.1.7 on 2023-06-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_alter_entidade_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entidade',
            index=models.Index(fields=['poder'], name='entidades_e_poder_bece8d_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['uf'], name='entidades_m_uf_77a9e0_idx'),
        ),
    ]
