# Generated by Django 4.1.7 on 2023-06-07 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.FloatField(default=0)),
                ('nivel', models.CharField(default='Inexistente', max_length=50)),
                ('essenciais', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionarios.questionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RespostaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_validacao', models.BooleanField(default=False)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('criterio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.criterioitem')),
                ('resposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionarios.resposta')),
                ('validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacoes.validacao')),
            ],
        ),
        migrations.CreateModel(
            name='LinkEvidenciaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_validacao', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('resposta_validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacoes.respostavalidacao')),
            ],
        ),
        migrations.CreateModel(
            name='JustificativaEvidenciaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa_validacao', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('resposta_validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacoes.respostavalidacao')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemEvidenciaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_validacao', models.FileField(upload_to='imagem_evidencia_validacao')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('resposta_validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacoes.respostavalidacao')),
            ],
        ),
    ]
