# Generated by Django 4.1.7 on 2023-06-27 18:35

from django.db import migrations, models
import validacoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('validacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemevidenciavalidacao',
            name='imagem_validacao',
            field=models.FileField(upload_to=validacoes.models.get_file_path),
        ),
    ]
