# Generated by Django 4.1.7 on 2023-04-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkEvidenciaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_validacao', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('resposta_validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacoes.respostavalidacao')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemEvidenciaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_validacao', models.FileField(upload_to='imagem_evidencia_validacao')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('resposta_validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacoes.respostavalidacao')),
            ],
        ),
    ]
