# Generated by Django 4.1.7 on 2023-04-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0005_alter_linkevidencia_link'),
        ('validacoes', '0002_linkevidenciavalidacao_imagemevidenciavalidacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostavalidacao',
            name='criterio_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionarios.criterioitem'),
            preserve_default=False,
        ),
    ]
