# Generated by Django 4.1.7 on 2023-05-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacoes', '0003_respostavalidacao_criterio_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaEvidenciaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa_validacao', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('resposta_validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacoes.respostavalidacao')),
            ],
        ),
    ]
