# Generated by Django 4.1.7 on 2023-05-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacoes', '0004_justificativaevidenciavalidacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validacao',
            options={'ordering': ('-created_at',)},
        ),
    ]
