# Generated by Django 4.1.7 on 2023-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacoes', '0005_alter_validacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostavalidacao',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
