# Generated by Django 4.1.7 on 2023-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacoes', '0007_validacao_indice_validacao_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao',
            name='essenciais',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='indice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='nivel',
            field=models.CharField(default='Inexistente', max_length=50),
        ),
    ]
